### ISSUE TITLE
Hashes generated for complex structs containing pointers don't seem to be correct

### ISSUE THREAD

**Issue by dikhan** [mitchellh/hashstructure#15]
Hi,

Looking for another pair of eyes here...Not sure what's wrong with this bit of code, but shouldn't the hash values be different?

````
	type Object struct {
		ID string
	}

	type TransactionExample struct {
		id    string
		objects []*Object
	}

	txn := TransactionExample{
		id:"txn1",
		objects: []*Object{},
	}

	txn2 := TransactionExample{
		id:"txn2",
		objects: []*Object{
			{ID: "test"},
		},
	}

	hash, _ := hashstructure.Hash(txn, nil)
	hash2, _ := hashstructure.Hash(txn2, nil)

	fmt.Println("Hashes:", hash, hash2)
````

Result:
````
Hashes: 5827385550866931895 5827385550866931895
````

Would appreciate some insight on this issue.

Thanks!
Dani

**Comment by mitchellh** [comment]
The library can't access unexported fields. Both `id` and `objects` unexported, so they have to be ignored. This is present in the docs already, but understandable if it was missed:

>    * Unexported fields on structs are ignored and do not affect the
>      hash value.

Let me know if there are any other questions!

**Comment by dikhan** [comment]
Thanks @mitchellh ! That worked :) , after exporting the fields now the hashed differ:

````
	type Object struct {
		ID string
	}

	type TransactionExample struct {
		ID    string
		Objects []*Object
	}

	txn := TransactionExample{
		ID:"txn1",
		Objects: []*Object{},
	}

	txn2 := TransactionExample{
		ID:"txn2",
		Objects: []*Object{
			{ID: "test"},
		},
	}

	hash, err := hashstructure.Hash(txn, nil)
	hash2, err1 := hashstructure.Hash(txn2, nil)


	fmt.Println("Hashes (txn):", hash, err)
	fmt.Println("Hashes (txn2):", hash2, err1)
````

Result:
````
Hashes (txn): 2701405128909120386 <nil>
Hashes (txn2): 7547503374618235440 <nil>
````

I totally missed the docs, my bad...quick suggestion, would be nice to add some debug when fields are ignored by the hash function so the user of the lib can understand what's going on internally.

Appreciate your help!
Dani

**Comment by dikhan** [comment]
Thx @mitchellh! Kind of new to go so appreciate the comments above ;) always open to learn new stuff. Regarding the ‘debug’ comment, makes sense not to compromise performance over better debugging considering the docs already cover this use case and more importantly being aware that it might affect other consumers using this lib in performance sensitive locations.

Thanks again for taking the time to explain the reasoning behind not having debug lines and also sharing the concerns driving that decision.

Dani
