### ISSUE TITLE
Unexported identifiers are not factored into hashing

### ISSUE THREAD

**Issue by dpup** [mitchellh/hashstructure#19]
```golang
func TestUnexportedFields(t *testing.T) {
	type str struct {
		v string
	}

	k1 := str{"123"}
	k2 := str{"456"}

	v1, _ := hashstructure.Hash(k1, nil)
	v2, _ := hashstructure.Hash(k2, nil)

	if v1 == v2 {
		t.Errorf("cache collision: %d vs %d", v1, v2)
	}
}
```

Expected: nothing
Actual: `cache collision: 15609384054371896546 vs 15609384054371896546`

This was surprising and unexpected. If this is intended behavior I suggest updating the documentation and considering making this an option.

**Comment by mitchellh** [comment]
Indeed, this is documented here as the first note: https://godoc.org/github.com/mitchellh/hashstructure#Hash

Go reflection can't see unexported fields unless you're in the same package (makes sense!) so hashstructure can't even see that they exist to make hashing decisions on them. To hashstructure it just looks like `type str struct {}`!

**Comment by dpup** [comment]
Ah, sorry for missing that. Maybe worth calling out in the readme too? I was expecting it to behave like `reflect.DeepEqual`.
