### ISSUE TITLE
ExampleHash test failure

### ISSUE THREAD

**Issue by onlyjob** [mitchellh/hashstructure#5]
With Golang 1.6 I'm getting the following test failure:

~~~~
=== RUN   ExampleHash 
--- FAIL: ExampleHash (0.00s) 
got: 
6691276962590150517 
want: 
8669281753891521642 
FAIL 
~~~~

**Comment by mitchellh** [comment]
Thanks, that's no good, I'm taking a look now.

**Comment by mitchellh** [comment]
Fixed: https://github.com/mitchellh/hashstructure/commit/95415bb46460fb895bab077547e323b42b0df8da

Normally I don't want to fix things like this, but I ran a `git bisect` and tests on various Go versions (1.4, 1.5, and 1.6) and they all report the same hash value. I noticed that the last commit just never updated the example. Really we don't want this value to ever change, but as we initially stabilized we had to a few times.

**Comment by onlyjob** [comment]
Thanks.
