### ISSUE TITLE
Embedded structs not working

### ISSUE THREAD

**Issue by jdoklovic** [mitchellh/hashstructure#8]
if i have something like:

```go
type MyBase struct {
    ID string
}

type MyThing struct {
    MyBase
   Name string
}

func doSomething() {
    thing1 := MyThing {
        ID: "one",
        Name: "me",
    }

    thing2 := MyThing {
        ID: "two",
        Name: "me",
    }
}
```
the ID field is not considered when hashing. and in the above example, thing1 and thing2 will have the same hash.

**Comment by jdoklovic** [comment]
actually, it's a result of the embedded struct being non-exported even though it's fields are.

e.g.
```go
type myBase struct {
    ID string
}

type MyThing struct {
    myBase
   Name string
}
```

**Comment by mitchellh** [comment]
This is working properly, hashstructure ignores unexported fields. Embedded structs are treated as unexported if they're not capitalized.
