### ISSUE TITLE
hashstructure.Hash is not concurrent safe

### ISSUE THREAD

**Issue by choleraehyq** [mitchellh/hashstructure#9]
So it cannot be used directly by multiple goroutines. Besides, there is only one global hasher under the hood, so I have to use a global lock to protect it.

**Comment by mitchellh** [comment]
I'm sorry I do not fully understand. Each call to `Hash` creates a new hasher and walker. You can call `Hash` safely concurrently. You cannot call it safely on the _same_ hasher, that is correct. Or, if you reuse the pointer for the hash options then that wouldn't be safe either. I'll update the docs to make this clear. Thanks!
